# Generated by Django 5.2.10 on 2026-01-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_parent_task_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_escalated',
            field=models.BooleanField(default=False),
        ),
    ]
